add_newline = false
format = """
[â”Œâ”€](bold purple)$directory$git_branch$git_state$git_status$status$fill$time
[â””â”€](bold purple)$character
"""

[git_status]
disabled = false
stashed = "ğŸ“¦"

[git_branch]
disabled = false

[git_state]
disabled = false

[time]
disabled = false
format = "[$time]($style) "

[status]
disabled = false
